TODAY
TODAY
Set_MDM_Auditoria_Portabilidad de DataServices
8:39 AM
9:21 AM
qudaría entonces con el OK
9:24 AM
9:24 AM
9:29 AM
sZwvc2hdcZxRKR4hovcXJp5R2APQq12qjKdv8HRh8h39GPLo2dXgDTAmrvyi
10:05 AM
12:08 PM
<?xml version="1.0" encoding="utf-16"?><Order_Pending_Query xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">  <document_type xmlns="http://www.etb.com.co/Gateway/MDM_Data_Services">CC</document_type>  <document_number xmlns="http://www.etb.com.co/Gateway/MDM_Data_Services">99103404</document_number>  <connection_number xmlns="http://www.etb.com.co/Gateway/MDM_Data_Services">3109999999</connection_number></Order_Pending_Query>
1:16 PM
Google analytics

tienda.app.etb.co

Copie el código que aparece a continuación y péguelo en todas las páginas de su sitio web.

Pegue este código tan alto en la etiqueta <head> de la página como sea posible:

 

<!-- Google Tag Manager -->

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':

new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],

j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=

'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);

})(window,document,'script','dataLayer','GTM-TJBGJL7');</script>

<!-- End Google Tag Manager -->

 

Pegue también este código inmediatamente después de la etiqueta <body> de apertura:

 

<!-- Google Tag Manager (noscript) -->

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TJBGJL7"

height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

<!-- End Google Tag Manager (noscript) -->

 

 

tiendadev.portallteqa.p.azurewebsites.net

Copie el código que aparece a continuación y péguelo en todas las páginas de su sitio web.

Pegue este código tan alto en la etiqueta <head> de la página como sea posible:

 

<!-- Google Tag Manager -->

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':

new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],

j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=

'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);

})(window,document,'script','dataLayer','GTM-WSVTGWP');</script>

<!-- End Google Tag Manager -->

 

Pegue también este código inmediatamente después de la etiqueta <body> de apertura:

 

<!-- Google Tag Manager (noscript) -->

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WSVTGWP"

height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

<!-- End Google Tag Manager (noscript) --> 

 

•              Bluekai

Encabezado à <script type="text/javascript" src="https://tags.bluekai.com/site/83829?ret=js&limit=1"></script>

Botones à html adjunto

 

 

•              Maxymiser 

Encabezado à <script type='text/javascript' src='//service.maxymiser.net/api/us/etb.com.co/42beff/mmapi.js'> </script>

 

•              Infinity à

 

•              Facebook à

Colocar en el Head:

<script>

        !function (f, b, e, v, n, t, s) {

            if (f.fbq) return; n = f.fbq = function () {

                n.callMethod ?

                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)

            };

            if (!f._fbq) f._fbq = n; n.push = n; n.loaded = !0; n.version = '2.0';

            n.queue = []; t = b.createElement(e); t.async = !0;

            t.src = v; s = b.getElementsByTagName(e)[0];

            s.parentNode.insertBefore(t, s)

        }(window, document, 'script',

            'https://connect.facebook.net/en_US/fbevents.js');

        fbq('init', '269326396764545');

        fbq('track', 'PageView');

</script>     

<noscript>

        <img height="1" width="1" style="display: none" src="https://www.facebook.com/tr?id=269326396764545&ev=PageView&noscript=1" />

    </noscript>

 

 

•              TagManager à

Copie el código que aparece a continuación y péguelo en todas las páginas de su sitio web.

Pegue este código tan alto en la etiqueta <head> de la página como sea posible:

<!-- Google Tag Manager -->

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':

new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],

j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=

'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);

})(window,document,'script','dataLayer','GTM-TDKHGJC');</script>

<!-- End Google Tag Manager -->

 

Pegue también este código inmediatamente después de la etiqueta <body> de apertura:

<!-- Google Tag Manager (noscript) -->

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TDKHGJC"

height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

<!-- End Google Tag Manager (noscript) -->
3:05 PM
